server:
  port: 8877

spring:
  application:
    name: SnowIdDemo
  datasource:
    url: jdbc:mysql://localhost:3306/db_snowid_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 2640
    driver-class-name: com.mysql.cj.jdbc.Driver